name: flutter_js
description: A Javascript engine to use with flutter.
  It uses Quickjs on Android and JavascriptCore on IOS
version: 0.8.5
homepage: https://github.com/abner/flutter_js
repository: https://github.com/abner/flutter_js

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0
dev_dependencies:
  test: ^1.29.0

flutter:
  plugin:
    platforms:
      android:
        package: io.abner.flutter_js
        pluginClass: FlutterJsPlugin
      ios:
        pluginClass: FlutterJsPlugin
      linux:
        pluginClass: FlutterJsPlugin
      macos:
        pluginClass: FlutterJsPlugin
      windows:
        pluginClass: FlutterJsPlugin

